---
Parameters:
  VpcId:
    Type: "AWS::EC2::VPC::Id"

Resources:
  sg:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "some_group_desc"
      VpcId:
        Ref: VpcId

  NestedGuy:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        VpcId:
          Ref: VpcId
      TemplateURL: "https://s3-us-west-2.amazonaws.com/stelligent-templates/exported_security_group.json"

  securityGroupIngress1234:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !GetAtt NestedGuy.Outputs.sg2output
      CidrIp: "10.1.2.3/32"
      FromPort: 38
      ToPort: 40
      IpProtocol: tcp
