---
Parameters:
  VpcId:
    Type: "AWS::EC2::VPC::Id"

Resources:
  sg2:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "some_group_desc"
      SecurityGroupIngress:
        CidrIp: "10.1.2.3/32"
        FromPort: 34
        ToPort: 36
        IpProtocol: tcp
      VpcId:
        Ref: VpcId
