---
Parameters:
  SubnetId:
    Type: "AWS::EC2::Subnet::Id"
    Default: subnet-d7a7a4eb
  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Default: vpc-e91e8490

Resources:
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      Subnets:
        - Ref: SubnetId
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '50'
      SecurityGroups:
        - !Ref httpSg

  httpSg:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "some_group_desc"
      SecurityGroupIngress:
        CidrIp: "0.0.0.0/0"
        FromPort: 80
        ToPort: 80
        IpProtocol: tcp
      VpcId:
        Ref: VpcId

